#!/bin/bash

if [ "$1" == "-h" ]; then
        echo \
"kc [参数列表...]
        执行org.jetbrains.kotlin.cli.jvm.K2JVMCompiler编译kotlin源文件
"
        exit 0
fi

if (($#==0)); then
        echo "交互式Kotlin解释器"
fi

#eval echo "'""$kotlin/*""'"
eval $(which jk) -cp '/cygdrive/e/kotlin/kotlinc/lib/kotlin-compiler.jar' org.jetbrains.kotlin.cli.jvm.K2JVMCompiler "$@"

